### ISSUE TITLE
Testes não encontrados

### ISSUE THREAD

**Issue by pedrogrigorio** [senapk/tko#4]
Estou tentando rodar um problema com testes, mas por algum motivo os testes não estão sendo encontrados.

[
![Captura de tela 2024-10-04 161747](https://github.com/user-attachments/assets/f86ed076-b9d5-4e97-b2f2-e5fcdce329f9)
](url)

**Comment by senapk** [comment]
Atualizamos o modelo de testes. Então você precisa atualizar o tko e baixar os testes novamentes.

**Comment by senapk** [comment]
Se estiver utilizando o tko play
Vai na questão e aperta b, ou utiliza a paleta de comandos.

**Comment by senapk** [comment]
Para atualizar o tko
pip install tko --force
ou se estiver na versão do ubuntu mais nova
pipx upgrade-all

**Comment by pedrogrigorio** [comment]
Atualizei com --force e deu certo agora, obrigado!
